# services that are to be connected (backend, frontend,)
services:
  # service 1: django-backend
  backend:
    # give a name to the container
    container_name: django-backend

    # give a name to the image
    image: django-docker

    # build from the dockerfile in the django dir
    build:
      context: ./django
      dockerfile: Dockerfile.backend

    # connect django directory to webapp dir of docker
    volumes:
      - ./django:/home/ubuntu/webapp

    # bind exposed port of the docker the backend server port
    ports:
      - "1920:8000"

  # service 2: react-frontend
  frontend:
    # give a name to the container
    container_name: react-frontend

    # give a name to the image
    image: react-vite-docker

    # build from the dockerfile in the react dir
    build:
      context: ./react
      dockerfile: Dockerfile.frontend

    # connect frontend dir inside react to the webapp dir of docker
    volumes:
      - ./react/frontend:/home/ubuntu/frontend

    # bind exposed port of the docker to the react (node server) port
    ports:
      - "2019:9000"
